# Generated by Django 5.1.7 on 2025-03-12 03:17
import os

from django.db import migrations
from django.contrib.auth import get_user_model


def create_superuser(apps, schema_editor):
    password = os.getenv("INITIAL_ADMIN_PASSWORD", "admin123")
    users = get_user_model().objects
    if not users.filter(username="admin").exists():
        users.create_superuser(username="admin", password=password, email="put@email.here")


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
